// R,P,S - Rock,Paper, Scissors

// Function outputs a random value between 0 - 3(exclusive) 
// values generated by function = (0,1,2)
let getComputerChoice = () => {

    // Math.random() outputs a float value inbetween 0 and 1(exclusive)
    // To over come this, Math.floor rounds down the float value. Multiplied with 3 for 3 values
    let choice = Math.floor(Math.random() * 3);
    return choice;
}

// Storing the value from the function into a variable
let computerChoice = getComputerChoice();


// Checking the values of computerChoice and accepting it if it's inbetween 0,1 and 2
let acceptance;
(computerChoice === 0 || computerChoice === 1 || computerChoice === 2) ? acceptance = true : acceptance === false;


// Function to convert integer(0,1,2) to value(Rock,Paper,Scissors)
// Function takes acceptance(T/F) and computerChoice(0,1,2)
let intToValue = (acceptance, computerChoice) => {

    let value;
    if (acceptance === true && computerChoice === 0){
        value = "Rock";
    }
    else if (acceptance === true && computerChoice === 1){
        value = "Paper";
    }
    else {
        value = "Scissors";
    }

    return value;
}

// Stored the value(R,P,S) into a variable
let finalComputerValue = intToValue(acceptance, computerChoice);
