// computerChoice Logic Code--------------------------------------------------------------------------------

// R,P,S - Rock,Paper, Scissors

// Function outputs a random value between 0 - 3(exclusive) 
// values generated by function = (0,1,2)
let getComputerChoice = () => {

    // Math.random() outputs a float value inbetween 0 and 1(exclusive)
    // To over come this, Math.floor rounds down the float value. Multiplied with 3 for 3 values
    let choice = Math.floor(Math.random() * 3);
    return choice;
}

// Storing the value from the function into a variable
let computerChoice = getComputerChoice();


// Checking the values of computerChoice and accepting it if it's inbetween 0,1 and 2
let acceptance;
(computerChoice === 0 || computerChoice === 1 || computerChoice === 2) ? acceptance = true : acceptance === false;


// Function to convert integer(0,1,2) to value(Rock,Paper,Scissors)
// Function takes acceptance(T/F) and computerChoice(0,1,2)
let intToValue = (acceptance, computerChoice) => {

    let value;
    if (acceptance === true && computerChoice === 0){
        value = "Rock";
    }
    else if (acceptance === true && computerChoice === 1){
        value = "Paper";
    }
    else {
        value = "Scissors";
    }

    return value;
}

// Stored the value(R,P,S) into a variable
let finalComputerValue = intToValue(acceptance, computerChoice);



// humanChoice Logic Code--------------------------------------------------------------------------------

// asks the user to input their choice
let user_input = prompt("Welcome to Rock-Paper-Scissors!\nTo play the game, Enter your choice below.")


// capitalizes user input
let capitalize = user_input.toUpperCase();


// Function to check if the capitalized version of the user input is rock, paper or scissors. 
// If it's not one of the three options then it returns an invalid input error message to the console.
let choiceChecker = (capitalize) => {
    
    let humanChoice;

    // Using ternary operator to mimic if/else statements
    (capitalize === "ROCK") ? humanChoice = "Rock":
    (capitalize === "PAPER") ? humanChoice = "Paper":
    (capitalize === "SCISSORS") ? humanChoice = "Scissors":
    humanChoice = "Invalid input, That input is not what I was expecting. Refresh browser and try again";

    return humanChoice;

    // The code below is another way of recreating the code above by using if/else statements 

    // if (capitalize === "ROCK"){
    //     humanChoice = capitalize;
    // }
    // else if (capitalize === "PAPER"){
    //     humanChoice = capitalize;
    // }
    // else if (capitalize === "SCISSORS"){
    //     humanChoice = capitalize;
    // }
    // else {
    //     humanChoice = "Invalid input, That input is not what I was expecting. Refresh browser and try again";
    // }
}

// finalHumanChoice holds the userinput choice for the game
let finalHumanChoice = choiceChecker(capitalize);

// Prints the choices chosen by player and computer to the console.
console.log(`For the game of Rock-Paper-Scissors \n You chose : ${finalHumanChoice} \n The browser chose : ${finalComputerValue}`);

// Initializing human and computer score to zero
let humanScore = 0;
let computerScore = 0;


