// computerChoice Logic Code--------------------------------------------------------------------------------

// R,P,S - Rock,Paper, Scissors

// Function outputs a random value between 0 - 3(exclusive) 
// values generated by function = (0,1,2)
let getComputerChoice = () => {

    // Math.random() outputs a float value inbetween 0 and 1(exclusive)
    // To over come this, Math.floor rounds down the float value. Multiplied with 3 for 3 values
    let choice = Math.floor(Math.random() * 3);
    return choice;
}

// Storing the value from the function into a variable
let computerChoice = getComputerChoice();


// Checking the values of computerChoice and accepting it if it's inbetween 0,1 and 2
let acceptance;
(computerChoice === 0 || computerChoice === 1 || computerChoice === 2) ? acceptance = true : acceptance === false;


// Function to convert integer(0,1,2) to value(Rock,Paper,Scissors)
// Function takes acceptance(T/F) and computerChoice(0,1,2)
let intToValue = (acceptance, computerChoice) => {

    let value;
    if (acceptance === true && computerChoice === 0){
        value = "Rock";
    }
    else if (acceptance === true && computerChoice === 1){
        value = "Paper";
    }
    else {
        value = "Scissors";
    }

    return value;
}

// Stored the value(R,P,S) into a variable
let finalComputerValue = intToValue(acceptance, computerChoice);



// humanChoice Logic Code--------------------------------------------------------------------------------

// asks the user to input their choice
// let user_input = prompt("Welcome to Rock-Paper-Scissors!\nTo play the game, Enter your choice below.")
let user_input;


// capitalizes user input
// let capitalize = user_input.toUpperCase();
let capitalize;


// Function to check if the capitalized version of the user input is rock, paper or scissors. 
// If it's not one of the three options then it returns an invalid input error message to the console.
let choiceChecker = (capitalize) => {
    
    let humanChoice;

    // Using ternary operator to mimic if/else statements
    (capitalize === "ROCK") ? humanChoice = "Rock":
    (capitalize === "PAPER") ? humanChoice = "Paper":
    (capitalize === "SCISSORS") ? humanChoice = "Scissors":
    humanChoice = "Invalid input, That input is not what I was expecting. Refresh browser and try again";

    return humanChoice;
}

// finalHumanChoice holds the userinput choice for the game
let finalHumanChoice = choiceChecker(capitalize);

//-------------------------------------------------------------------------------

let entireGame = (humanChoice, computerChoice) => {

    let playRound = (humanChoice, computerChoice) => {
    
        let human = humanChoice;
        let computer = computerChoice;
        
        switch(true){
            
            // Case: Rock Win
            case (human === "Rock" && computer === "Scissors"):return {human : human, computer: computer}

            // Case: Rock Tie
            case (human === "Rock" && computer === "Rock"):return {human : human, computer: computer}
    
            // Case: Rock Lose
            case (human === "Rock" && computer === "Paper"): return {human : human, computer: computer}
    
            // Case: Paper Win
            case (human === "Paper" && computer === "Rock"): return {human : human, computer: computer}
    
            // Case: Paper Tie
            case (human === "Paper" && computer === "Paper"): return {human : human, computer: computer}
    
            // Case: Paper Lose
            case (human === "Paper" && computer === "Scissors"): return {human : human, computer: computer}
    
            // Case: Scissors Win
            case (human === "Scissors" && computer === "Paper"): return {human : human, computer: computer}
    
            // Case: Scissors Tie
            case (human === "Scissors" && computer === "Scissors"): return {human : human, computer: computer}
    
            // Case: Scissors Lose
            case (human === "Scissors" && computer === "Rock"): return {human : human, computer: computer}
    
            default: console.log("Invalid Input, Refresh Browser and try again");
            break;
        }
    }



    for(let i = 0; i < 5; i++){
        let human = humanChoice;
        let computer = computerChoice;

        // Initializing human and computer score to zero
        let humanScore = 0;
        let computerScore = 0;

        user_input = prompt("Welcome to Rock-Paper-Scissors!\nTo play the game, Enter your choice below.");
        capitalize = user_input.toUpperCase();

        playRound(human, computer);
        // let {humanResult, computerResult} = playRound(human, computer);
        // console.log(`human chose: ${humanResult}\ncomputer chose: ${computerResult}`);
    }
}
entireGame(finalHumanChoice, finalComputerValue);




